services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

    Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
      calls:
        - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]


  caledit.service.auth:
    class: DanielGausi\CalendarEditorBundle\Services\CheckAuthService
    public: true